Update react.yml

diff --git a/.github/workflows/react.yml b/.github/workflows/react.yml
--- a/.github/workflows/react.yml
+++ b/.github/workflows/react.yml
@@ -24,16 +24,34 @@ jobs:
           bun-version: latest
 
       - name: 📥 Install dependencies with Bun (with cache)
-        run: bun install --cwd packages/supabase-kit-react
+        run: |
+          if [ -d packages/supabase-kit-react ]; then
+            bun install --cwd packages/supabase-kit-react
+          else
+            echo "Directory packages/supabase-kit-react not found!"
+            exit 1
+          fi
 
       - name: 💅 Lint
-        run: cd packages/supabase-kit-react/ && bun lint
+        run: |
+          if [ -d packages/supabase-kit-react ]; then
+            cd packages/supabase-kit-react/ && bun lint
+          else
+            echo "Directory packages/supabase-kit-react not found!"
+            exit 1
+          fi
 
       # - name: 🧪 Test
       #   run: bun test --ci --coverage --max-workers=2
 
       - name: 🛠️ Build
-        run: cd packages/supabase-kit-react/ && bun run build
+        run: |
+          if [ -d packages/supabase-kit-react ]; then
+            cd packages/supabase-kit-react/ && bun run build
+          else
+            echo "Directory packages/supabase-kit-react not found!"
+            exit 1
+          fi
 
       - name: 🚀 Publish to npm
         uses: JS-DevTools/npm-publish@v1
